apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${artifactId}-service
  labels:
    app: ${artifactId}-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${artifactId}-service
  template:
    metadata:
      labels:
        app: ${artifactId}-service
    spec:
      containers:
      - name: ${artifactId}-service
        image: moreyog/${artifactId}-service:${version}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ${artifactId}-service
  labels:
    app: ${artifactId}-service
    spring-boot: "true"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ${artifactId}-service
  type: ClusterIP